### ISSUE TITLE
plans to support React?

### ISSUE THREAD

**Issue by miguelalarcos** [deanius/meteor-promise#10]
Hi, I'm wondering if there will be any plans to support promises on React. I'm thinking in something like this:

```coffee
Session.set 'arg1', 1
Session.set 'arg2', 2

@Main = React.createClass
    mixins : [ReactMeteorData]
    getMeteorData: ->
        data = {}
        arg1 = Session.get 'arg1'
        arg2 = Session.get 'arg2'
        data.promise = Meteor.call('add', arg1, arg2)
        data
    render: ->
        <div>
            hello: {@data.promise}
        </div>
```
Thanks.

**Comment by deanius** [comment]
This package is agnostic to Blaze or React - I don't know how React deals with Promises, you're on your own with that for now :)  Also, FYI the push I'm about to release forces you back to `Meteor.promise` instead of patching `Meteor.call`, hopefully MDG will make that style official eventually.
