### ISSUE TITLE
Replacing to okgrow:promise should we update our current promisses?

### ISSUE THREAD

**Issue by ssoulless** [deanius/meteor-promise#13]
Hi, I wonder if we should update the syntax of the promises, once we replace to the okgrow:promise package  can any promise broke? I ask this since I have more than +300 promises in my app it is pretty big so Im afraid to update to the new package and broke my current promises that are working ok.

**Comment by jrudio** [comment]
Just a heads up, moving to `okgrow:promise` took away server-side `Meteor.promise`.

**Comment by deanius** [comment]
yes, @jrudio - on the server, Meteor.call doesn't require a callback, running synchronously in a fiber - so having a Promise for it in the server seemed redundant.

**Comment by deanius** [comment]
@ssoulless - No veo ningún razón porqué no funcionaran. Why don't you try it and see ? The only thing you may notice is if you rely on the toString() version of a Promise, which has changed. Other than that  - just renaming and additional APIs that's all :)

**Comment by jrudio** [comment]
Thanks @deanius, I feel dumb for using it like that on the server.
haha

**Comment by deanius** [comment]
@jrudio ha :+1:

**Comment by ssoulless** [comment]
Thanks Just for let you know, I just replaced this package for the new one, I was afraid of make my app crash, or have to update promises markup, however everything kept working in the normal fashion, so you can update with confidence =)

**Comment by deanius** [comment]
Thanks for the report @ssoulless !
