### ISSUE TITLE
Provide HTTP.callPromise on the server?

### ISSUE THREAD

**Issue by SeanBannister** [deanius/meteor-promise#15]
I was wondering if you'd consider providing HTTP.callPromise on the server so its possible to use the same code on the client and the server without re-writing it. We often move bits of code between each and we're therefore trying to write code that runs in each.

**Comment by deanius** [comment]
I didn't include it initially (because Fibers), but I'd take a PR for that.. Basically changing `package.js` to load certain files on `['client', 'server']`, and extending the test suite to cover that.

**Comment by deanius** [comment]
Incidentally, this is from the NPM ecosystem (so to use in client in Meteor you'd need `cosmos:browserify`), but it's a well proven library I'd recommend https://www.npmjs.com/package/request-promise.

I'm no longer thinking it's such a good idea to maintain enhancement's to Meteor's oddball HTTP package, so I'm recommending people use the raw node ecosystem which is in general more robust and tested than the average Meteor package.

**Comment by steph643** [comment]
+1 for this feature

**Comment by deanius** [comment]
The `fetch` (or `fetch-wg`) package is the best way to do this. This package is no longer maintained.
