### ISSUE TITLE
okgrow vs deanius meteor-promise?

### ISSUE THREAD

**Issue by richb-hanover** [deanius/meteor-promise#16]
How are this version of meteor-promise and the okgrow version (https://github.com/okgrow/meteor-promise) related?

It appears that this version has been worked on more recently - it is preferred?

**Comment by deanius** [comment]
This is the one which will be maintained going forward. Incidentally I'm looking for a new maintainer, who can even take on full ownership. If you know anyone who'd be interested.

**Comment by richb-hanover** [comment]
Thanks for the clarification about deanius:meteor-promise being the supported version.
