### ISSUE TITLE
cosmos:browserify dependency

### ISSUE THREAD

**Issue by optilude** [deanius/meteor-promise#26]
This package adds a dependency on cosmos:browserify, which I assume is unnecessary (maybe even detrimental?) after Meteor 1.3. Should it be removed?

**Comment by deanius** [comment]
Go nuts - lots of things about this package went obsolete as Meteor incorporated Promises and things - I'm no longer maintaining it.

**Comment by defionscode** [comment]
Figured it may interest you to know that in Feb of this year Meteor's blog featured an article referencing this package as a way to do client side promises. 

https://blog.meteor.com/using-promises-on-the-client-in-meteor-fb4f1c155f84

**Comment by deanius** [comment]
Ha that's great @defionscode, thanks!
