### ISSUE TITLE
Could I check "is ready" to wait the result like pub/sub?

### ISSUE THREAD

**Issue by thearabbit** [deanius/meteor-promise#8]
I create the `Meteor.method()` to generate reports, so I want to show the `spinner` or any `loading...` when the serve is running.
Could I check "is ready" to wait the result like pub/sub?
Please example for me.

**Comment by deanius** [comment]
Interesting point - could you show me more code ? If you're using the PromiseHelper, I just pushed an update that lets you pass an additional loading text, in addition to the function to wrap. If that's not your use case, I'm not sure I can help - post some code and let's see though :)

```
Template.foo.helpers({
  report: PromiseHelper(function(){ return Meteor.call(method, args); }, "loading...")
});
```

**Comment by thearabbit** [comment]
```js
// Server
Meteor.methods({
    add: function () {
        Meteor._sleepForMs(1000);
        return 'Welcome to Promise Call';
    }

// Client
<template name="myTpl">
   {{#if myValue}}
      {{myValue}}
   {{else}}
      {{> spinner}}
   {{/if}}

Template.myTpl.helpers({
   myValue: PromiseHelper(function(){
      return Meteor.call('add');
   })
})
</template>
```

**Comment by thearabbit** [comment]
Could I use loading with `spinner` template?
`PromiseHelper(function(){ return Meteor.call(method, args); }, Template.spinner)`

**Comment by deanius** [comment]
I think you could do so like this: Blaze.toHTML(Template.spinner)
```js
Template.myTpl.helpers({
   myValue: PromiseHelper(function(){
      return Meteor.call('add');
   }, Blaze.toHTML(Template.spinner))
})
```
Let me know if that works for you - I'm not sure if that functionality is something I'd take on internally, but I'd document it as a valid use case if it works!

**Comment by thearabbit** [comment]
It don't work. It show `[object object]`.

**Comment by deanius** [comment]
Sorry, I could not reproduce this - if you have a more full example I'd love to see it. Thanks for all the great questions.
